---
- name: Disable SSH password auth
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  register: sshd_config

- name: change ssh port
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#Port 22"
    line: Port "{{ sshport }}"
  #register: sshd_config

- name: Restart SSH Daemon
  service:
    name: sshd
    state: restarted
  #when: sshd_config.changed