---
# vars file for ./nginx-proxy-manager
container: "npm"
username: "npm"
group: "npm"
uid: "2001"
gid: "2001"
image: "jc21/nginx-proxy-manager:latest"
http: "80"
https: "443"
gui: "81"
host: "database"
dbport: "3306"
USER: "npm"
PASSWORD: "npm"
NAME: "npm"

### MYSQL files ###

DB_container: "npm_database"
DB_image: "jc21/mariadb-aria:latest"
SQL_DB_ROOT_PASSWORD: "npm"
SQL_DATABASE: "npm"

### volumes ##
config: "/srv/server-configs/proxy-manager/:/data"
letsencrypt: "/srv/server-configs/letsencrypt:/etc/letsencrypt"
mysql_config: "/srv/server-configs/mysql:/var/lib/mysql"
