---
# tasks file for ./plex
### create group and user for the plex docker container ###
- name: create "{{ group }}" group
  group:
    name: "{{ group }}"
    gid: "{{ gid }}"
    state: present

- name: create "{{ username }}" user
  user:
    name: "{{ username }}"
    uid: "{{ uid }}"
    group: "{{ group }}"
    create_home: no

### set permissions for the plex media directorys ###

#- name: set permissions for "{{ plex-1 }}"
#  file:
#    path: "{{ plex-1 }}"
#    owner: root
#    group: plex
#    mode: 520

#- name: set permissions for "{{ plex-2 }}"
#  file:
#    path: "{{ plex-2 }}"
#    owner: root
#    group: plex
#    mode: 520

#- name: set permissions for "{{ plex-3 }}"
#  file:
#    path: "{{ plex-3 }}"
#    owner: root
#    group: plex
#    mode: 520

### download image and create docker container ###
- name: docker pull plex image
  community.docker.docker_container:
    name: plex-image
    image: "{{ image }}"

- name: pull plex image and start the docker Container
  community.docker.docker_container:
    name: "{{ container }}"
    image: "{{ image }}"
    state: started
    env: 
      UID: "{{ uid }}"
      GID: "{{ gid }}"
      TZ:  "{{ timezone }}"
    volumes:
      - "{{ plex_config }}:/config"
      - "{{ transcode }}:/transcode"
      - "{{ tv }}:/TV-1:ro"
      - "{{ tv2 }}:/TV-2:ro"
      - "{{ tv3 }}:/TV-3:ro"
      - "{{ movies_4K }}:/4K-Movies-1:ro"
      - "{{ movies_4K2 }}:/4K-Movies-2:ro"
      - "{{ movies_4K3 }}:/4K-Movies-3:ro"
      - "{{ mcu }}:/MCU-1:ro"
      - "{{ mcu2 }}:/MCU-2:ro"
      - "{{ HD_movies }}:/HD-movies-1:ro"
      - "{{ HD_movies2 }}:/HD-movies-2:ro"
      - "{{ HD_movies3 }}:/HD-movies-3:ro"
      - "{{ movies }}:/Movies:ro"
      - "{{ christmas_movies }}:/Christmas:ro"
      - "{{ musicals }}:/Musicals:ro"
      - "{{ anime }}:/Anime-1:ro"
      - "{{ anime2 }}:/Anime-2:ro"
      - "{{ kids_movies }}:/kids-movies:ro"
      - "{{ music }}:/Music:ro"
    
